name: Intro_Github_Actions

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
   build:

      runs-on: ubuntu-latest

      steps:
        - name: ckeck repo
          uses: actions/checkout@v3
        - name: Log to Dockerhub
          uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
          with:
           username: ${{secrets.DOCKER_USERNAME}}
           password: ${{secrets.DOCKER_PASSWORD}}
        - name: Build docker image
          run: docker build . --Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}
        - name: Push to dockerhub
          run: docker push ${{ secrets.DOCKER_USERNAME }}/my_first_repo
        
